[package]
name = "gpt-fat32-disk-image-create"
version = "0.1.0"
authors = ["Stephen Sherratt <stephen@sherra.tt>"]
edition = "2018"

[dependencies]
simon = "0.4"
mini_gpt = { version = "0.1", path = "../mini-gpt" }
mini_fat = { version = "0.1", path = "../mini-fat" }
